### PR TITLE
Allow the default DataSource to be overridden

### PR DESCRIPTION
**Pull request by eygraber**
This helps with overridding the `HttpDataSource` if it needs to modified (e.g. adding request headers).

### CODE REVIEW

**Comment by brianwernick** [comment]
This should probably be added to all the other RenderBuilders as well

**Comment by eygraber** [comment]
Will update shortly. 

Have you thought about making the `RenderBuilder`s into more of a builder pattern? That would make them much easier to customize, and use. If you're OK with that I can take a stab at it.

**Comment by brianwernick** [comment]
Yeah, I think that's a good idea.  And I'll take any help I can get :)

**Comment by eygraber** [comment]
Just for book keeping purposes, this would close https://github.com/brianwernick/ExoMedia/issues/86

**Comment by eygraber** [comment]
Is it OK that [`HlsRenderBuilder.AsyncRendererBuilder`](https://github.com/brianwernick/ExoMedia/pull/123/files#diff-2c0564b11c7526eedfb5ba4272338caeL99) and [`SmoothStreamRenderBuilder.AsyncRendererBuilder`](https://github.com/brianwernick/ExoMedia/pull/123/files#diff-ef88920a04cd23b16e5b70bf1c4bba91L99) were made non-`static`?

**Comment by brianwernick** [comment]
That's fine.  They are only referenced by the `HlsRenderBuilder` and `SmoothStreamRenderBuilder` themselves anyways.

**Pull request merged**
