### PR TITLE
Add RenderBuilder for Smooth Streaming support

### PR DESCRIPTION
**Pull request by se-bastiaan**
Only added to the VideoView implementation, this should also be usable for the AudioPlayer.
But I only have good test videostreams.

### CODE REVIEW

**Comment by brianwernick** [comment]
This PR looks good but there is a merge conflict with the DASH changes

**Comment by se-bastiaan** [comment]
I'll fix that

**Comment by se-bastiaan** [comment]
Fixed, needs #54 now first though.

**Comment by brianwernick** [comment]
:+1:

**Pull request merged**
