### PR TITLE
Toggle video controls on click

### PR DESCRIPTION
**Pull request by Saketme**
- [ X] This pull request follows the coding standards

###### This PR changes:
 - Toggles the video controls on click instead of always showing them. 

Edit: @brianwernick I'm unable to understand why Github is showing me 29 new commits instead of just 1 when I'm comparing against `dev_v4`. Can you help me out with this?

### CODE REVIEW

**Comment by brianwernick** [comment]
You need to rebase your branch

**Comment by Saketme** [comment]
It's already rebased. I already have your most recent commits:

screen shot 2017-04-02 at 9 40 27 pm

**Comment by brianwernick** [comment]
That's odd :/ . Anyways, this has been a feature that I've meant to add for a while but keep getting distracted then forget what I was doing. Because you closed this PR (I'm assuming due to the git oddities) I went ahead and just added the functionality to the `dev_v4` branch

**Comment by Saketme** [comment]
Haha that also works. Thanks!

**Pull request closed without merging**
