### PR TITLE
Support for Side-Loading Subtitles from a Uri

### PR DESCRIPTION
**Pull request by masterwok**
###### Addresses issue #.
- [ ] This pull request follows the coding standards

###### This PR changes:
 - Added support for side-loading subtitles from a Uri ([https://google.github.io/ExoPlayer/guide.html#side-loading-a-subtitle-file](https://google.github.io/ExoPlayer/guide.html#side-loading-a-subtitle-file)

### CODE REVIEW

**Comment by brianwernick** [comment]
Just doing a quick overview of the changes it looks like there's two parts
1. The caption listener/rendering portion and
2. The side loaded subtitle Uri

I'll try to get to a full review later this week but on first inspection it looks like a good direction. Thanks for the PR :)

**Comment by masterwok** [comment]
No problem, glad to help out!

**Comment by olucurious** [comment]
@brianwernick it will be great to have this feature in ExoMedia, can you please do a full review of the PR

**Comment by brianwernick** [comment]
As I mentioned above (a few months ago, sorry for the delay) there are two main changes in this
  1. Closed caption listener & rendering
  2. Side loaded subtitle Uri

Because this would be merged in to master that will be for the next minor release (4.2) I only feel comfortable about merging in the changes for `1` and not the breaking api changes for `2`. If you can break this out in to 2 separate PR's I can get the first part merged in so that the PR it's sitting around until the 5.0 work begins

**Comment by juliafu1** [comment]
Do you have plans to merge this PR? thanks

**Pull request closed without merging**
