### PR TITLE
Transform VideoControls as an Interface

### PR DESCRIPTION
**Pull request by Gounlaf**
###### Fixes issue #.
- [x] This pull request follows the coding standards

###### This PR changes: 
* Update library: make `EMVideoView` expect an Interface for `videoControls` parameter, allowing those to be totally custom
* Update demo according to library modifications

### CODE REVIEW

**Comment by brianwernick** [comment]
This should be made against the 3.1 branch as it is not a bug fix (won't be patched in the 3.0.x releases)

**Comment by Gounlaf** [comment]
@brianwernick Ok. Let me change that.

**Comment by brianwernick** [comment]
Oops, I didn't notice that you had updated the base branch already. I'll look at this when I get some time this evening or tomorrow

**Comment by brianwernick** [comment]
What issue are you attempting to fix by making the `VideoControls` an interface instead of an abstract class in which everything can be overridden?

**Comment by se-bastiaan** [comment]
What I don't like is that the expected controls implementation in `PlaylistManager` and `MediaService` is  an instance of `BaseVideoControls`, thus instead of implementing the `VideoControls` interface you're supposed to override `BaseVideoControls`. Which renders the interface obsolete imho. You can just extend the `BaseVideoControls` if you want a custom controls UI and it'll always work, not just when you're not using `PlaylistManager` or `MediaService`.

**Comment by Gounlaf** [comment]
Hi,

@brianwernick 
> What issue are you attempting to fix by making the VideoControls an interface instead of an abstract class in which everything can be overridden?

In the default implementation, buttons are too specific (`ImageButton`, and I needed Buttons only, because I would like to use Android-Iconics library) ; default drawable became obsolete in my case ; I don't need `titleViewtitleView`, `subTitleViewsubTitleView` and `descriptionViewdescriptionView`. The default controls are "too much".

That's why I thank the "default" controls should be an implementation of an interface.

Like you said (and se-bastiaan also), I can override all I want. But I thank using an interface is more flexible to do a total custom interface.

@se-bastiaan: the PlaylistManager is part of the demo module, not the library ; so, yes, the demo use the default controls provided. `library` only refer to `VideoControls` interface

**Comment by brianwernick** [comment]
With your examples you only need to extend the `VideoControls` to provide drawables for the buttons (which really should already be methods, but that's a different issue); AndroidIconics can generate an `IconicsDrawable` that you can use.  The text views (title, subTitle, description) won't be displayed unless you set content.

By providing the abstract class that you can customize it is implied that, while you can make changes you are responsible for issues that may cause. With an interface it would imply that it should "just work" which may not be the case due to the multiple internal listeners (touch, seek, animations, etc.). It won't be worth it to support an interface in the long run for the small percentage of users that would like an interface over the abstract class.

**Comment by Gounlaf** [comment]
Well... You can close it.

**Pull request closed without merging**
